### ISSUE TITLE
Allow attributes (class, style, etc) for all tags in one time

### ISSUE THREAD

**Issue by bastien70** [tgalopin/html-sanitizer-bundle#25]
Hello, is it possible to allow the tags attributes (like class, style, etc) for specifics (or all ) tags in one time in yaml ?

Currently, I've to do this in my config file : 

```yaml
html_sanitizer:
    default_sanitizer: 'default'
    sanitizers:
        default:
            extensions:
                - 'basic'
                - 'list'
                - 'table'
                - 'image'
                - 'code'
                
            tags:
                span:
                    allowed_attributes:
                        - style
                        - class

                table:
                    allowed_attributes:
                        - style
                        - class

                thead:
                    allowed_attributes:
                        - style
                        - class
```
