### ISSUE TITLE
Troubleshooting custom extension

### ISSUE THREAD

**Issue by mycodeself** [tgalopin/html-sanitizer-bundle#6]
Im having problems with a custom sanitizer extension that i created for a project im working on. The extension is manually register with the tag name using YAML like this:

```
    app.sanitizer.iframe_custom:
        class: App\Sanitizer\CustomIframeExtension
        tags:
          - { name: html_sanitizer.extension }
```
The problem its that this extension is not register though the sanitizer builder.

I debug the code and i found that in the HtmlSanitizerExtension when it call to "findTaggedServiceIds('html_sanitizer.extension')" my sanitizer extension service its not found.

If i debug my kernel, and use the findTaggedServiceIds('html_sanitizer.extension') in my Kernel.php its found the service by tag... its like when HtmlSanitizerExtension is loaded my services arent currently loaded.

Some suggestion of what can i do?

Thanks and regards!
